import { Database, Globe2, ShieldAlert, Users } from 'lucide-react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Card } from '../../components/ui';
import { MOCK_TENANTS } from '../../data/mockData';
const growth = [{ month: 'Jan', value: 62 }, { month: 'Fev', value: 74 }, { month: 'Mar', value: 89 }, { month: 'Abr', value: 103 }, { month: 'Mai', value: 126 }, { month: 'Jun', value: 142 }];
export function AdminDashboard() {
  const cards = [[Globe2, 'Tenants ativos', '142'], [Users, 'Usuários totais', '48,5 mil'], [Database, 'Armazenamento', '1,4 TB'], [ShieldAlert, 'Alertas', '2']] as const;
  return <div className="space-y-7"><header><p className="text-sm font-semibold text-brand-600">Administração global</p><h1 className="text-3xl font-bold">Saúde da plataforma</h1><p className="text-slate-500">Visão executiva do ecossistema Imuniza+</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon, label, value]) => <Card key={label}><Icon className="text-brand-600"/><p className="mt-4 text-sm text-slate-500">{label}</p><strong className="mt-1 block text-3xl">{value}</strong></Card>)}</div><div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="mb-5 font-bold">Crescimento de tenants</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={growth}><XAxis dataKey="month"/><YAxis hide/><Tooltip/><Line type="monotone" dataKey="value" stroke="currentColor" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Card><Card><h2 className="mb-4 font-bold">Tenants recentes</h2><div className="space-y-3">{MOCK_TENANTS.map((tenant) => <div key={tenant.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div><p className="font-semibold">{tenant.name}</p><p className="text-xs text-slate-500">{tenant.plan} · {tenant.users} usuários</p></div><Badge status={tenant.status}>{tenant.status}</Badge></div>)}</div></Card></div></div>;
}
